server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:liquibase/db.changelog-master.xml
    enabled: true

external:
  certificate-generator:
    uri: http://localhost:8090